# Generated by Django 5.1.6 on 2026-06-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_result_jodi_alter_contestentry_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='contestentry',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contestentry',
            name='possible_win',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contestentry',
            name='win_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contestentry',
            name='entry_type',
            field=models.CharField(max_length=30),
        ),
    ]
