# Generated by Django 5.1.6 on 2026-06-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_contestentry_amount_contestentry_is_winner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestentry',
            name='is_winner',
        ),
        migrations.RemoveField(
            model_name='contestentry',
            name='possible_win',
        ),
        migrations.RemoveField(
            model_name='contestentry',
            name='win_rate',
        ),
        migrations.AlterField(
            model_name='contestentry',
            name='entry_type',
            field=models.CharField(max_length=50),
        ),
    ]
