# Generated by Django 5.1.6 on 2026-06-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_contestentry_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contestentry',
            name='entry_type',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('JODI', 'Jodi'), ('PANA', 'Pana')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contestentry',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=20),
        ),
    ]
